/*=============================================================================
  Table 7: Descriptive statistics
  Input : scores for anallysis_sep5.xlsx, sheet Final
  Output: outputs/Table7_descriptive_statistics.rtf
          outputs/Table7_descriptive_statistics.log

  Before running, replace the project_dir below with the folder containing
  the Excel workbook. Forward slashes work on Windows and macOS.
=============================================================================*/

version 17.0
clear all
set more off

local project_dir "CHANGE_TO_FOLDER_CONTAINING_THE_EXCEL_FILE"
cd "`project_dir'"

capture mkdir "outputs"
capture log close
log using "outputs/Table7_descriptive_statistics.log", text replace

/* Import the source data. */
import excel using "scores for anallysis_sep5.xlsx", ///
    sheet("Final") firstrow case(lower) clear

/* Use the manuscript variable names. */
rename chatgpt_human_new GPT_H
rename human Human

label variable GPT_H "GPT_H"
label variable Human "Human"

/* Reproducibility checks for the supplied analysis file. */
confirm numeric variable GPT_H Human
assert !missing(GPT_H, Human)
count
assert r(N) == 70
isid firmyear

/* Display the statistics in Stata. */
tabstat GPT_H Human, statistics(n mean sd min max) ///
    columns(statistics) format(%9.2f)

/*
  estpost and esttab are supplied by the estout package. Install the package
  once, if necessary, by running: ssc install estout
*/
capture which estpost
if _rc {
    display as error "The estout package is required. Run: ssc install estout"
    exit 499
}

/* Export the publication-style table as a Word-compatible RTF file. */
estpost summarize GPT_H Human

esttab using "outputs/Table7_descriptive_statistics.rtf", replace ///
    cells("count(fmt(0)) mean(fmt(2)) sd(fmt(2)) min(fmt(2)) max(fmt(2))") ///
    collabels("Obs" "Mean" "Std" "Min" "Max") ///
    label nonumber nomtitle noobs ///
    title("Table 7: Descriptive statistics") ///
    addnotes("Note: GPT_H denotes the score generated by ChatGPT following prompt refinement. Human denotes the score derived from expert human judgement.")

/* Confirm the underlying unrounded values in the log. */
quietly summarize GPT_H
display as text "GPT_H: N=" %3.0f r(N) ///
    ", Mean=" %12.8f r(mean) ", SD=" %12.8f r(sd) ///
    ", Min=" %6.2f r(min) ", Max=" %6.2f r(max)

quietly summarize Human
display as text "Human: N=" %3.0f r(N) ///
    ", Mean=" %12.8f r(mean) ", SD=" %12.8f r(sd) ///
    ", Min=" %6.2f r(min) ", Max=" %6.2f r(max)

log close

/* Expected rounded output from the supplied workbook:

   Variable     Obs     Mean      Std      Min      Max
   GPT_H         70     70.61     9.09     46.00    90.00
   Human         70     73.07    10.31     45.00    91.00
*/
